// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace iNVEST
{
	public partial class iNVESTViewStock : UIViewController
	{
		public iNVESTViewStock (IntPtr handle) : base (handle)
		{
		}
	}
}
